name: rms
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.4.28+20

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  connectivity_plus: ^4.0.2
  overlay_support: ^1.2.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  rename: ^3.0.2
  url_launcher: ^6.3.0
  app_settings: ^5.1.1
  image_picker: ^1.1.2
  open_file: ^3.5.4
  path_provider: ^2.1.3  
  device_info_plus: ^10.1.2
  flutter_local_notifications: ^18.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  percent_indicator: ^4.2.3
  google_maps_flutter: ^2.1.0
  intl: ^0.19.0
  geocoding: ^2.0.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  syncfusion_flutter_datepicker: ^24.2.9
  flutter_spinkit: ^5.2.0
  loader_overlay: ^2.3.2
  geolocator: 11.0.0
  # flutter_local_notifications: ^9.0.0
  permission_handler: ^10.3.0
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/appstore.png"  

    


  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - images/
